project:
  type: website

website:
  title: "Ayya Keshet"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - publications/publications.qmd

    tools:
      - icon: twitter
        href: https://twitter.com/AyyaKeshet
      - icon: linkedin
        href: https://www.linkedin.com/in/ayya-keshet-a048768a/
      - icon: google
        href: https://scholar.google.com/citations?user=iFB8x-IAAAAJ&hl=en
      - icon: github
        href: https://github.com/ayya-keshet
  
  twitter-card:
     creator: "@AyyaKeshet"
     site: "@AyyaKeshet"
     card-style: summary_large_image
  site-url: "https://ayya-keshet.github.io/"

format:
  html:
    theme:
      light: darkly
      dark: Minty
    css: styles.css
    toc: true

execute:
  freeze: auto