---
title: "Publications"
---
## Journal publications  

**Continuous glucose monitoring and intrapersonal variability in fasting glucose**\
Smadar Shilo, Ayya Keshet, Hagai Rossman, Anastasia Godneva, Yeela Talmor-Barkan, Yaron Aviv, Eran Segal.\
_Nature Medicine 2024_ [[paper] (https://www.nature.com/articles/s41591-024-02908-9)]

**Genome-wide association studies and polygenic risk score phenome-wide association studies across complex phenotypes in the human phenotype project*\
Zachary Levine, Iris Kalka, Dmitry Kolobkov, Hagai Rossman, Anastasia Godneva, Smadar Shilo, Ayya Keshet, Daphna Weissglas-Volkov, Tal Shor, Alon Diament, Yeela Talmor-Barkan, Yaron Aviv, Tom Sharon, Adina Weinberger, Eran Segal.\
_Med 2024_ [[paper] (https://www.cell.com/med/abstract/S2666-6340(23)00400-2)]

**CGMap: Characterizing continuous glucose monitor data in thousands of non-diabetic individuals**\
Ayya Keshet, Smadar Shilo, Anastasia Godneva, Yeela Talmor-Barkan, Yaron Aviv, Eran Segal, Hagai Rossman.\
_Cell Metabolism 2023_ [[paper](https://www.cell.com/cell-metabolism/pdf/S1550-4131(23)00129-8.pdf)] 

**Wearable and digital devices to monitor and treat metabolic diseases**\
Ayya Keshet, Lee Reicher, Noam Bar, Eran Segal.\
_Nature Metabolism 2023_ [[paper] (https://www.nature.com/articles/s42255-023-00778-y)]

**PyMSM: Python package for Competing Risks and Multi-State models for Survival Data**\
Hagai Rossman, Ayya Keshet, Malka Gorfine.\
_Journal of Open Source Software 2022_ [[paper](https://joss.theoj.org/papers/10.21105/joss.04566)] [[code](https://github.com/hrossman/pymsm)] 

**Estimating the effect of cesarean delivery on long term childhood health across two countries**\
Ayya Keshet, Hagai Rossman, Smadar Shilo, Shiri Barbash-Hazan, Guy Amit, Maytal Bivas-Benita, Chen Yanover, Irena Girshovitz, Pinchas Akiva, Avi Ben-Haroush, Eran Hadar, Arnon Wiznitzer, Eran Segal.\
[[paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0268103)] [[code](https://github.com/ayya-keshet/Causal-Survival-Analysis)]

**A framework for identifying regional outbreak and spread of COVID-19 from one-minute population-wide surveys**\
Hagai Rossman, Ayya Keshet, Smadar Shilo, Amir Gavrieli, Tal Bauman, Ori Cohen, Ran Balicer, Benjamin Geiger, Yuval Dor, Eran Segal.\
_Nature Medicine 2020_ [[paper](https://www.nature.com/articles/s41591-020-0857-9)]

**Longitudinal symptom dynamics of COVID-19 infection**\
Barak Mizrahi, Smadar Shilo, Hagai Rossman, Nir Kalkstein, Karni Marcus, Yael Barer, Ayya Keshet, Na'ama Shamir-Stein, Varda Shalev, Anat Ekka Zohar, Gabriel Chodick, Eran Segal.\
_Nature Communications 2020_ [[paper](https://www.nature.com/articles/s41467-020-20053-y)] [[blog](https://naturemicrobiologycommunity.nature.com/posts/tracking-the-longitudinal-dynamics-of-symptoms-of-covid-19-infection-in-primary-care)]

**Building an International Consortium for Tracking Coronavirus Health Status**\
Segal et. al.\
_Nature Medicine 2020_ [[paper](https://www.nature.com/articles/s41591-020-0929-x)]

**A Prediction Model to Prioritize Individuals for a SARS-CoV-2 Test Built from National Symptom Surveys**\
Saar Shoer, Tal Karady, Ayya Keshet, Smadar Shilo, Hagai Rossman, Amir Gavrieli, Tomer Meir, Amit Lavon, Dmitry Kolobkov, Iris Kalka, Anastasia Godneva, Ori Cohen, Adam Kariv, Ori Hoch, Mushon Zer-Aviv, Noam Castel, Anat Ekka Zohar, Angela Irony, Benjamin Geiger, Dorit Hizi, Varda Shalev, Ran Balicer, Eran Segal.\
_Med 2020_ [[paper](https://www.sciencedirect.com/science/article/pii/S2666634020300192)]

**Cohort profile: 10K - a large-scale prospective longitudinal study in Israel**\
Smadar Shilo, Noam Bar, Ayya Keshet, Yeela Talmor-Barkan, Hagai Rossman, Anastasia Godneva, Yaron Aviv, Yochai Edlitz, Lee Reicher, Dmitry Kolobkov, Bat Chen Wolf, Maya Lotan-Pompan, Kohava Levi, Ori Cohen, Hila Saranga, Adina Weinberger, Eran Segal.\
_European Journal of Epidemiology 2021_ [[paper](https://link.springer.com/article/10.1007/s10654-021-00753-5)]
 
**Stress-related emotional and behavioural impact following the first COVID-19 outbreak peak**\
Asaf Benjamin, Yael Kuperman, Noa Eren, Ron Rotkopf, Maya Amitai, Hagai Rossman, Smadar Shilo, Tomer Meir, Ayya Keshet, Orit Nuttman-Shwartz, Eran Segal & Alon Chen. \
_Molecular Psychiatry 2021_ [[paper](https://www.nature.com/articles/s41380-021-01219-6)]

**Anosmia and other SARS-CoV-2 positive test-associated symptoms, across three national, digital surveillance platforms as the COVID-19 pandemic and response unfolded: an observation study**\
Sudre, Keshet, et. al.\
_Lancet Digital Health 2021_ [[paper](https://www.sciencedirect.com/science/article/pii/S2589750021001151)]

**A-to-I RNA Editing Affects lncRNAs Expression after Heat Shock**\
Roni Haas, Nabeel S. Ganem, Ayya Keshet, Angela Orlov, Alla Fishman, Ayelet T. Lamm.\
_Genes 2018_ [[paper] (https://www.mdpi.com/2073-4425/9/12/627)]


## Preprints

**The effect of a national lockdown in response to COVID-19 pandemic on the prevalence of clinical symptoms in the population**\
Ayya Keshet, Amir Gavrieli, Hagai Rossman, Smadar Shilo, Tomer Meir, Tal Karady, Amit Lavon, Dmitry Kolobkov, Iris Kalka, Saar Shoer, Anastasia Godneva, Ori Cohen, Adam Kariv, Ori Hoch, Mushon Zer-Aviv, Noam Castel, Anat Ekka Zohar, Angela Irony, Benjamin Geiger, Yuval Dor, Dorit Hizi, Ran Balicer, Varda Shalev, Eran Segal.\
[[preprint](https://www.medrxiv.org/content/10.1101/2020.04.27.20076000v2)]

**FrackyFrac: A Standalone UniFrac Calculator**\
Amit Lavon, Smadar Shilo, Ayya Keshet, Eran Segal.\
[[preprint] (https://arxiv.org/abs/2404.11087)]


## Conference & poster presentations

A Multimodal Dataset of 21,412 Recorded Nights for Sleep and Respiratory Research\ 
Alon Diament, Maria Gorodetski, Adam Jankelow, Ayya Keshet, Tal Shor, Daphna Weissglas-Volkov, Hagai Rossman, Eran Segal.\
Neural Information Processing Systems (NeurIPS) [Machine Learning in Health workshop](https://arxiv.org/abs/2311.08979), 2023

Leveraging nationwide data and domain expertise to infer causal effect of cesarean section birth on long term pediatric health\
Ayya Keshet, Hagai Rossman, Shiri Hazan, Smadar Shilo, Eran Hadar, Avi Ben-Haroush, Arnon Wiznitzer, Eran Segal.\
[Machine Learning in Real Life workshop ICLR 2020](https://sites.google.com/nyu.edu/ml-irl-2020/home)

Rapid deployment of a nationwide, one-minute, online symtpoms survey during the outbreak and spread of COVID-19 - framework and application
Keshet et. al.
[ICML 2020 Workshop, Healthcare Systems, Population Health, and the Role of Health-Tech](https://sites.google.com/view/hsys2020)

Who Should We Test for COVID-19? A Triage Model Built from National Symptom Surveys (Spotlight)
Shoer et. al.
[ICML 2020 Workshop, Healthcare Systems, Population Health, and the Role of Health-Tech](https://sites.google.com/view/hsys2020)
